### ISSUE TITLE
Project templates invisible in VS2019

### ISSUE THREAD

**Issue by lucyllewy** [iolevel/peachpie-vs#1]
The Project templates are not in the list of new project types in the new VS2019 new project window. Neither PeachPie nor PHP nor "PHP (PeachPie)" are available in the languages dropdown. Filtering either Web or Console does not reveal the project templates. The only way to get to them is to type "PeachPie" into the search field. This means that discoverability is a problem.

**Comment by jakubmisek** [comment]
sadly, this is a known issue of VS2019. Custom project templates are not "categoried" within their new Platform/Language groups.

You have to manually type "PHP" into the search box.

**Comment by lucyllewy** [comment]
Looks like some improvements in 2019 have just landed, but I'm not sure if they're sufficient: https://devblogs.microsoft.com/visualstudio/build-visual-studio-templates-with-tags-for-efficient-user-search-and-grouping/

**Comment by jakubmisek** [comment]
we'll try to add some metadata and see what happens

**Comment by jakubmisek** [comment]
seems `<LanguageTag>` still cannot be of value `PHP`

**Comment by jakubmisek** [comment]
the recent updates of VS probably fix the behavior, we'll release the updatet extension soon:
![image](https://user-images.githubusercontent.com/842150/60767319-c6202c00-a0b6-11e9-9f9d-616e463a034c.png)
thanks Daniel! closing the issue
